//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MatrixTestSoft.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MATRIXTESTSOFT_DIALOG       102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_UARTTOUDP            129
#define IDD_DIALOG_PORTMONITORING       130
#define IDD_DIALOG_SAMPLE               131
#define IDD_DIALOG_PORTMONITORING_REC   133
#define IDD_DIALOG_PORTMONITORING_SEND  134
#define IDI_ICON1                       135
#define IDI_ICON2                       136
#define IDC_TAB_ITEMS                   1000
#define IDC_BUTTON_SAVEFILEPATH         1000
#define IDC_EDIT_SAMPLETIME             1000
#define IDC_COMBO_SERIALPORT_COM        1001
#define IDC_BUTTON_STARTSAVE            1001
#define IDC_BUTTOT_STARTSAMPLE          1001
#define IDC_COMBO_SERIALPORT_BAUD       1002
#define IDC_BUTTON_STOPSAVE             1002
#define IDC_BUTTON_STOPSAMPLE           1002
#define IDC_MSCOMM1                     1003
#define IDC_EDIT_RECEIVE                1003
#define IDC_BUTTON_SAVEFILEPATH2        1003
#define IDC_BUTTON_SERIALPORT_OPEN      1004
#define IDC_BUTTON_RESET                1004
#define IDC_BUTTON_SERIALPORT_CLOSE     1005
#define IDC_EDIT_SAVESIZE               1005
#define IDC_STATIC_AXIS_X               1005
#define IDC_IPADDRESS_UARTTOUDP         1006
#define IDC_STATIC_AXIS_Y               1006
#define IDC_EDIT_PORT_UARTTOUDP         1007
#define IDC_IPADDRESS1                  1007
#define IDC_CHECK_GRAPHVIEW1            1007
#define IDC_EDIT_PORT_UARTTOUDP2        1008
#define IDC_EDIT_PORT_REC               1008
#define IDC_IPADDRESS2                  1008
#define IDC_CHECK_GRAPHVIEW2            1008
#define IDC_EDIT_AIMRCVPORT1            1009
#define IDC_CHECK_GRAPHVIEW3            1009
#define IDC_EDIT_AIMRCVPORT2            1010
#define IDC_CHECK_GRAPHVIEW4            1010
#define IDC_EDIT_AIMSENDPORT1           1011
#define IDC_EDIT_AIMSENDPORT2           1012
#define IDC_TAB_PORTMONITORING          1013
#define IDC_STATIC_RECFRAMENUM          1014
#define IDC_STATIC_SENDFRAMENUM         1015
#define IDC_STATIC_HEADFRAMENUM         1015
#define IDC_GRAPHSHOW1                  1015
#define IDC_EDIT_HEADFRAMESHOW          1016
#define IDC_BUTTON_PORTMONITORING_OPEN  1016
#define IDC_GRAPHSHOW2                  1016
#define IDC_STATIC_IPSETRETURNNUM       1017
#define IDC_BUTTON2                     1017
#define IDC_BUTTON_PORTMONITORING_CLOSE 1017
#define IDC_GRAPHSHOW3                  1017
#define IDC_EDIT_IPSETRETURNSHOW        1018
#define IDC_GRAPHSHOW4                  1018
#define IDC_STATIC_TAILFRAMENUM         1019
#define IDC_EDIT1                       1019
#define IDC_EDIT_SENDPORT               1019
#define IDC_EDIT_TAILFRAMESHOW          1020
#define IDC_CHECK_PORTDISTRIBUTION      1020
#define IDC_STATIC_TAILTIMERETURNNUM    1021
#define IDC_CHECK1                      1021
#define IDC_CHECK_MATRIXNETWORK         1021
#define IDC_EDIT_TAILTIMERETURNSHOW     1022
#define IDC_BUTTON1                     1022
#define IDC_STATIC_DELAYTIMERETURNNUM   1023
#define IDC_STATIC_AVERAGE1             1023
#define IDC_EDIT_DELAYTIMERETURNSHOW    1024
#define IDC_STATIC_AVERAGE2             1024
#define IDC_STATIC_ADCSETRETURNNUM      1025
#define IDC_STATIC_AVERAGE3             1025
#define IDC_EDIT_ADCDATARECSHOW         1026
#define IDC_STATIC_AVERAGE4             1026
#define IDC_STATIC_HEARTBEATFRAMENUM    1027
#define IDC_BUTTON3                     1027
#define IDC_EDIT_HEARTBEATFRAMESHOW     1028
#define IDC_STATIC_INSTRUMENT1          1028
#define IDC_STATIC_IPSETNUM             1029
#define IDC_STATIC_INSTRUMENT2          1029
#define IDC_EDIT_IPSETSHOW              1030
#define IDC_STATIC_INSTRUMENT3          1030
#define IDC_STATIC_ADCDATARECNUM        1031
#define IDC_STATIC_MAX1                 1031
#define IDC_STATIC_MAX2                 1032
#define IDC_STATIC_TAILTIMESETNUM       1033
#define IDC_STATIC_MAX3                 1033
#define IDC_EDIT_TAILTIMESETSHOW        1034
#define IDC_STATIC_MAX4                 1034
#define IDC_STATIC_DELAYTIMESETNUM      1035
#define IDC_STATIC_INSTRUMENT4          1035
#define IDC_EDIT_DELAYTIMESETSHOW       1036
#define IDC_CHECK2                      1036
#define IDC_CHECK_HEARTBEAT             1036
#define IDC_STATIC_ADCSETNUM            1037
#define IDC_EDIT_ADCSETSHOW             1038
#define IDC_STATIC_RMS1                 1039
#define IDC_STATIC_MIN1                 1040
#define IDC_SCROLLBAR_GRAPHVIEW         1041
#define IDC_STATIC_RMS2                 1042
#define IDC_BUTTON_STARTNOISE           1043
#define IDC_STATIC_RMS3                 1044
#define IDC_STATIC_RMS4                 1045
#define IDC_STATIC_MIN2                 1050
#define IDC_STATIC_MIN3                 1051
#define IDC_STATIC_MIN4                 1052
#define IDC_BUTTON_STOPNOISE            1057
#define IDC_CHECK_NOISE1                1058
#define IDC_CHECK_NOISE2                1059
#define IDC_CHECK_NOISE3                1060
#define IDC_CHECK_NOISE4                1061

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1037
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
