//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by line.rc
//
#define IDC_GRID_EDIT                   1
#define IDC_GRID_LIST_LBBUTTONDOWN      1
#define IDC_GRID_LIST                   2
#define IDC_GRID_LIST_DBLCLK            2
#define IDC_EDIT_AUXILIARYDESCR         11
#define IDC_EDIT_ABSOLUTESPREAD         12
#define IDC_EDIT_DELAYBETWEENTEST       13
#define IDC_EDIT_RECORDLENGTH           14
#define IDC_EDIT_TESTFILENB             15
#define IDC_CHECK_RECORDRESULTS         16
#define IDD_ABOUTBOX                    100
#define IDS_MAIN_TOOLBAR                101
#define IDS_STRING102                   102
#define IDS_STRING103                   103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDS_STRING105                   105
#define IDS_STRING106                   106
#define IDS_STRING107                   107
#define IDS_STRING108                   108
#define IDS_STRING109                   109
#define IDS_STRING110                   110
#define IDS_STRING111                   111
#define IDS_STRING112                   112
#define IDS_STRING113                   113
#define IDS_STRING114                   114
#define IDS_STRING115                   115
#define IDS_STRING116                   116
#define IDS_STRING117                   117
#define IDS_STRING118                   118
#define IDS_STRING119                   119
#define IDS_STRING120                   120
#define IDS_STRING121                   121
#define IDS_STRING122                   122
#define IDS_STRING123                   123
#define IDS_STRING124                   124
#define IDS_STRING125                   125
#define IDS_STRING126                   126
#define IDS_STRING127                   127
#define IDR_MAINFRAME                   128
#define IDR_line3TYPE                   129
#define IDS_STRING130                   130
#define IDR_POPUP_TOOLBAR               131
#define IDS_STRING131                   131
#define IDR_POPUP_MDITABS               132
#define IDS_STRING132                   132
#define IDR_POPUP_DROP_MDITABS          133
#define IDS_STRING133                   133
#define IDS_STRING134                   134
#define IDS_STRING135                   135
#define IDS_STRING136                   136
#define IDS_STRING137                   137
#define IDS_STRING138                   138
#define IDS_STRING139                   139
#define IDS_STRING140                   140
#define IDS_STRING141                   141
#define IDS_STRING142                   142
#define IDS_STRING143                   143
#define IDS_STRING144                   144
#define IDS_STRING145                   145
#define IDS_STRING146                   146
#define IDS_STRING147                   147
#define IDS_STRING148                   148
#define IDS_STRING149                   149
#define IDS_STRING150                   150
#define IDB_TOOLBAR256                  151
#define IDS_STRING151                   151
#define IDS_STRING152                   152
#define IDD_DIALOG_FORMLINESETUP        160
#define IDR_MENU_MATRIX_VIEW_GRAPH      161
#define IDR_MENU_MATRIX_VIEW_LIST       162
#define IDR_POPUP_GRAPHVIEW_INSTRUMENT  163
#define IDR_POPUP_GRAPHVIEW_SENSOR      164
#define IDR_TOOLBAR_MATRIX_VIEW         165
#define IDR_TOOLBAR1                    167
#define IDR_TOOLBAR_MATRIX_INSTRUMENT_GRAPH_TOP 170
#define IDR_TOOLBAR_MATRIX_GRAPH_BOTTOM 171
#define IDD_DIALOG_SETINSTRUMENT        172
#define IDR_EDIT                        172
#define IDR_TOOLBAR_MATRIX_SENSOR_GRAPH_TOP 173
#define IDD_DIALOG_SURVEYSETUP          174
#define IDD_DIALOG_LAYOUTSETUP          175
#define IDD_DIALOG_TESTBASESETUP        176
#define IDD_DIALOG_SPREADSETUP          177
#define IDD_DIALOG_TESTSETUP            178
#define IDD_DIALOG_LOOKSETUP            179
#define IDD_DIALOG_SELECTSHOTPOINT      180
#define IDR_POPUP_OUTPUT                181
#define IDD_DIALOG_STATUS               181
#define IDB_FDU_BITMAP_8                187
#define IDB_FDU_BITMAP16                188
#define IDB_FDU_BITMAP24                189
#define IDB_FDU_BITMAP48                190
#define IDB_AUL_BITMAP8                 191
#define IDB_AUL_BITMAP16                192
#define IDB_AUL_BITMAP24                193
#define IDB_AUL_BITMAP48                194
#define IDB_AUX_BITMAP8                 195
#define IDB_AUX_BITMAP16                196
#define IDB_AUX_BITMAP24                197
#define IDB_AUX_BITMAP48                198
#define IDC_BUTTON_RESET                1027
#define IDC_BUTTON_ADD                  1028
#define IDC_BUTTON_CHANGE               1029
#define IDC_BUTTON_DELETE               1030
#define IDC_STATIC_TAB                  1032
#define IDC_BUTTON_APPLY                1033
#define IDC_BUTTON_GO                   1040
#define IDC_COMPANY_URL                 1041
#define IDC_STATIC_MESSAGE              1053
#define ID_VIEW_CUSTOMIZE               32770
#define ID_VIEW_TOOLBARS                32771
#define ID_VIEW_OUTPUT                  32804
#define ID_MDI_NEW_VERT_GROUP           32841
#define ID_MDI_NEW_HORZ_TAB_GROUP       32842
#define ID_MDI_MOVE_TO_PREV_GROUP       32843
#define ID_MDI_CANCEL                   32844
#define ID_MDI_MOVE_TO_NEXT_GROUP       32845
#define ID_FILE_PRINT32850              32850
#define ID_EDIT_COPY32851               32851
#define ID_EDIT_PASTE32852              32852
#define ID_MATRIX_SURVEYSETUP           32853
#define ID_MATRIX_LAYOUTSETUP           32854
#define ID_MATRIX_SPREADSETUP           32855
#define ID_MATRIX_LOOKSETUP             32856
#define ID_MATRIX_FORMLINESETUP         32857
#define ID_MATRIX_TESTBASESETUP         32858
#define ID_MATRIX_TESTSETUP             32859
#define ID_MATRIX_INSTRUMENTGRAPH       32860
#define ID_MATRIX_SENSORGRAPH           32861
#define ID_MATRIX_SEISMONITORGRAPH      32862
#define ID_MATRIX_INSTRUMENTLIST        32863
#define ID_MATRIX_SENSORLIST            32864
#define ID_SEARCH_                      32865
#define IDR_POPUP_GRAPHVIEW_INSTRUMENT_PROPERTIES 32866
#define IDR_POPUP_GRAPHVIEW_INSTRUMENT_SETAUXILIARY 32867
#define IDR_POPUP_GRAPHVIEW_INSTRUMENT_SETLOWBOXOFDETOUR 32868
#define IDR_POPUP_GRAPHVIEW_INSTRUMENT_SETHIGHBOXOFDETOUR 32869
#define IDR_POPUP_GRAPHVIEW_INSTRUMENT_FORMLINE 32870
#define IDR_POPUP_GRAPHVIEW_SENSOR_PROPERTIES 32871
#define IDR_POPUP_GRAPHVIEW_SENSOR_SETAUXILIARY 32872
#define IDR_POPUP_GRAPHVIEW_SENSOR_MUTE 32873
#define ID_MATRIX_VIEWGRAPH             32874
#define ID_MATRIX_VIEWLIST              32875
#define ID_BUTTON_MATRIX_INSTRUMENT_GRAPH_POINT 32877
#define ID_BUTTON_MATRIX_INSTRUMENT_GRAPH_LINE 32878
#define ID_BUTTON_MATRIX_INSTRUMENT_GRAPH_CROSS 32879
#define ID_BUTTON_MATRIX_INSTRUMENT_GRAPH_POWER 32880
#define ID_BUTTON_MATRIX_INSTRUMENT_GRAPH_COLLECT 32881
#define ID_VIEW_VIEW_TOOLBAR            32887
#define ID_EMPTY                        32888
#define ID_BUTTON_MATRIX_GRAPH_ZOOMIN   32992
#define ID_BUTTON_MATRIX_GRAPH_ZOOMOUT  32994
#define ID_BUTTON_MATRIX_GRAPH_LINENAMELABEL 32995
#define ID_BUTTON_MATRIX_GRAPH_LINENAME 32996
#define ID_BUTTON_MATRIX_GRAPH_POINTNBLABEL 32997
#define ID_BUTTON_MATRIX_GRAPH_POINTNB  32998
#define IDC_COMBO_INSTRUMENT_TYPE       32999
#define IDC_BUTTON_ADD_PREVIOUS         33000
#define IDC_BUTTON_ADD_NEXT             33001
#define IDR_POPUP_GRAPHVIEW_INSTRUMENT_SETMARKER 33002
#define IDR_POPUP_GRAPHVIEW_INSTRUMENT_SETINSTRUMENT 33003
#define ID_BUTTON_MATRIX_SENSOR_GRAPH_TESTMARKER 33028
#define ID_BUTTON_MATRIX_SENSOR_GRAPH_SENSORQCTYPELABEL 33029
#define ID_BUTTON_MATRIX_SENSOR_GRAPH_SENSORQCTYPELIST 33030
#define ID_BUTTON_MATRIX_SENSOR_GRAPH_LOOK 33031
#define ID_BUTTON_MATRIX_SENSOR_GRAPH_QCGO 33032
#define ID_BUTTON_MATRIX_SENSOR_GRAPH_QCLIST 33033
#define ID_BUTTON_MATRIX_SENSOR_GRAPH_QCLABEL 33034
#define IDC_BUTTON_APPLYALL             33035
#define IDC_BUTTON_APPLYSENSOR          33036
#define IDC_BUTTON_REVERSE              33037
#define IDC_BUTTON_CLEAR                33038
#define IDC_BUTTON_SELECTSHOTPOINT      33039
#define ID_BUTTON_MATRIX_INSTRUMENT_GRAPH_TESTMARKER 33882
#define ID_BUTTON_MATRIX_INSTRUMENT_GRAPH_QCLABEL 33883
#define ID_BUTTON_MATRIX_INSTRUMENT_GRAPH_QCLIST 33884
#define ID_BUTTON_MATRIX_INSTRUMENT_GRAPH_QCGO 33885
#define ID_BUTTON_MATRIX_INSTRUMENT_GRAPH_LOOK 33886
#define ID_BUTTON_MATRIX_SENSOR_GRAPH_NBSTART 40000
#define ID_BUTTON42877                  42877
#define ID_EDIT_                        42879
#define IDC_CHECK_LOOKAUTO              42888
#define IDC_CHECK_RESISTANCE            42889
#define IDC_CHECK_TILT                  42890
#define IDC_CHECK_LEAKAGE               42891
#define IDC_OK                          42892
#define IDC_CANCEL                      42893
#define IDB_BITMAP_GO                   42894
#define IDB_BITMAP_LOOK                 42895
#define IDR_TOOLBAR_MATRIX_FIELD        42896
#define IDB_TOOLBAR_MATRIX_FIELD_HC     42897
#define IDR_TOOLBAR_MATRIX_SETUP        42898
#define IDR_TOOLBAR_MATRIX_SEISMONITOR_GRAPH_TOP 42899
#define IDB_BREAK                       42900
#define ID_BUTTON_MATRIX_FIELD_ON       42901
#define ID_BUTTON_MATRIX_FIELD_OFF      42902
#define ID_BUTTON_MATRIX_SEISMONITOR_GRAPH_SENSORQCTYPELABEL 42903
#define ID_BUTTON_MATRIX_SEISMONITOR_GRAPH_SENSORQCTYPELIST 42904
#define ID_BUTTON_MATRIX_SEISMONITOR_GRAPH_TESTMARKER 42905
#define ID_BUTTON_MATRIX_SEISMONITOR_GRAPH_LIMITLABEL 42906
#define ID_BUTTON_MATRIX_SEISMONITOR_GRAPH_LIMIT 42907
#define ID_BUTTON_MATRIX_SEISMONITOR_GRAPH_LIMITVALUE 42908
#define ID_BUTTON_MATRIX_SEISMONITOR_GRAPH_SEISMONITOR 42909
#define ID_FILE_SEARCH                  42910
#define IDR_MENU_IMAGES                 42911
#define ID_VIEW_SETUP_TOOLBAR           42912
#define ID_VIEW_FIELD_TOOLBAR           42913
#define ID_BUTTON_MATRIX_FIELD_ON_LABEL 42914
#define ID_BUTTON_MATRIX_FIELD_OFF_LABEL 42915
#define ID_BUTTON_MATRIX_FIELD_ON_GRAPH 42917
#define ID_BUTTON_MATRIX_FIELD_OFF_GRAPH 42918
#define ID_OUTPUT_GOTO_ERROR            42919
#define ID_MATRIX_FILE_TOOLBAR          42920
#define ID_MATRIX_EDIT_TOOLBAR          42921

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        199
#define _APS_NEXT_COMMAND_VALUE         42880
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
