//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MatrixTestSoft.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MATRIXTESTSOFT_DIALOG       102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_UARTTOUDP            129
#define IDD_DIALOG_PORTMONITORING       130
#define IDD_DIALOG_SAMPLE               131
#define IDD_DIALOG_PORTMONITORING_REC   133
#define IDD_DIALOG_PORTMONITORING_SEND  134
#define IDD_DIALOG_GRAPHSHOW            139
#define IDD_DIALOG_ADCSETTINGS          140
#define IDD_DIALOG_ADCDATASHOW          141
#define IDD_DIALOG_EEPROM               142
#define IDB_BITMAP_FDU1                 143
#define IDB_BITMAP_LAUX2                144
#define IDB_BITMAP_LAUX1                145
#define IDB_BITMAP_FDU2                 146
#define IDB_BITMAP_LAUL1                147
#define IDB_BITMAP2                     148
#define IDB_BITMAP_LAUL2                148
#define IDC_TAB_ITEMS                   1000
#define IDC_BUTTON_SAVEFILEPATH         1000
#define IDC_EDIT_SAMPLETIME             1000
#define IDC_COMBO_SERIALPORT_COM        1001
#define IDC_BUTTON_STARTSAVE            1001
#define IDC_BUTTOT_STARTSAMPLE          1001
#define IDC_COMBO_SERIALPORT_BAUD       1002
#define IDC_BUTTON_STOPSAVE             1002
#define IDC_BUTTON_STOPSAMPLE           1002
#define IDC_MSCOMM1                     1003
#define IDC_EDIT_RECEIVE                1003
#define IDC_BUTTON_SAVEFILEPATH2        1003
#define IDC_BUTTON_SERIALPORT_OPEN      1004
#define IDC_BUTTON_RESET                1004
#define IDC_BUTTON_SERIALPORT_CLOSE     1005
#define IDC_EDIT_SAVESIZE               1005
#define IDC_STATIC_AXIS_X               1005
#define IDC_IPADDRESS_UARTTOUDP         1006
#define IDC_STATIC_AXIS_Y               1006
#define IDC_EDIT_PORT_UARTTOUDP         1007
#define IDC_IPADDRESS1                  1007
#define IDC_EDIT_PORT_UARTTOUDP2        1008
#define IDC_EDIT_PORT_REC               1008
#define IDC_IPADDRESS2                  1008
#define IDC_EDIT_AIMRCVPORT1            1009
#define IDC_EDIT_AIMRCVPORT2            1010
#define IDC_EDIT_AIMSENDPORT1           1011
#define IDC_EDIT_AIMSENDPORT2           1012
#define IDC_TAB_PORTMONITORING          1013
#define IDC_STATIC_RECFRAMENUM          1014
#define IDC_STATIC_SENDFRAMENUM         1015
#define IDC_STATIC_HEADFRAMENUM         1015
#define IDC_EDIT_HEADFRAMESHOW          1016
#define IDC_BUTTON_PORTMONITORING_OPEN  1016
#define IDC_STATIC_IPSETRETURNNUM       1017
#define IDC_BUTTON_PORTMONITORING_CLOSE 1017
#define IDC_EDIT_IPSETRETURNSHOW        1018
#define IDC_STATIC_TAILFRAMENUM         1019
#define IDC_EDIT_SENDPORT               1019
#define IDC_EDIT_TAILFRAMESHOW          1020
#define IDC_CHECK_PORTDISTRIBUTION      1020
#define IDC_EDIT_SENDPORT2              1020
#define IDC_EDIT_ADCSAVEFRAMENB         1020
#define IDC_STATIC_TAILTIMERETURNNUM    1021
#define IDC_CHECK_MATRIXNETWORK         1021
#define IDC_EDIT_TAILTIMERETURNSHOW     1022
#define IDC_BUTTON_SETADC               1022
#define IDC_STATIC_DELAYTIMERETURNNUM   1023
#define IDC_EDIT_DELAYTIMERETURNSHOW    1024
#define IDC_STATIC_ADCSETRETURNNUM      1025
#define IDC_EDIT_ADCDATARECSHOW         1026
#define IDC_EDIT_ERRORCODERETURNSHOW    1026
#define IDC_STATIC_HEARTBEATFRAMENUM    1027
#define IDC_BUTTON_TIMECAL              1027
#define IDC_EDIT_HEARTBEATFRAMESHOW     1028
#define IDC_STATIC_IPSETNUM             1029
#define IDC_EDIT_IPSETSHOW              1030
#define IDC_STATIC_ADCDATARECNUM        1031
#define IDC_STATIC_ERRORCODERETURNNUM   1031
#define IDC_STATIC_TAILTIMESETNUM       1032
#define IDC_EDIT_TAILTIMESETSHOW        1033
#define IDC_STATIC_DELAYTIMESETNUM      1034
#define IDC_EDIT_DELAYTIMESETSHOW       1035
#define IDC_CHECK_HEARTBEAT             1035
#define IDC_STATIC_ADCSETNUM            1036
#define IDC_VSCROLLBAR                  1036
#define IDC_EDIT_ADCSETSHOW             1037
#define IDC_STATIC_LAUX                 1038
#define IDC_SCROLLBAR_GRAPHVIEW         1039
#define IDC_STATIC_GRAPHSHOW            1185
#define IDC_BUTTON_SETBYHAND            1185
#define IDC_EDIT_HPFLOW                 1186
#define IDC_EDIT_HPFHIGH                1187
#define IDC_CHECK_SHOWMESSAGE           1187
#define IDC_COMBO_SYNC                  1188
#define IDC_STATIC_COLLECTSYSTIMERETURNNUM 1188
#define IDC_COMBO_MODE                  1189
#define IDC_STATIC_ADCREC               1189
#define IDC_STATIC_ADCRECNUM            1189
#define IDC_EDIT_ADCDATA                1190
#define IDC_BUTTON_GRAPHEXE             1190
#define IDC_COMBO_SPS                   1191
#define IDC_LIST_INSTRUMENT             1191
#define IDC_COMBO_PHS                   1192
#define IDC_LIST_UPDATA                 1192
#define IDC_COMBO_FILTER                1193
#define IDC_BUTTON_MOVELEFT_ALL         1193
#define IDC_COMBO_MUX                   1194
#define IDC_BUTTON_MOVELEFT_ONE         1194
#define IDC_COMBO_CHOP                  1195
#define IDC_BUTTON_MOVERIGHT_ALL        1195
#define IDC_COMBO_SPS6                  1196
#define IDC_BUTTON_MOVERIGHT_ONE        1196
#define IDC_COMBO_PGA                   1197
#define IDC_STATIC_INSTRUMENT_NUM       1197
#define IDC_STATIC_UPDATA_NUM           1198
#define IDC_EDIT_READ_MAX               1199
#define IDC_EDIT_READ_TOTAL             1200
#define IDC_EDIT_READ_ADDR              1201
#define IDC_EDIT_WRITE_MAX              1202
#define IDC_EDIT_WRITE_TOTAL            1203
#define IDC_EDIT_WRITE_ADDR             1204
#define IDC_LIST_FAIL                   1205
#define IDC_STATIC_FAIL_NUM             1206
#define IDC_BUTTON_LOADFILE             1207
#define IDC_CHECK_BROADCAST_WRITE       1208
#define IDC_BUTTON_WRITE_EEPROM         1209
#define IDC_BUTTON_START_CHECK          1210
#define IDC_LIST_MESSAGE                1211
#define IDC_LIST_SUCCESS                1212
#define IDC_STATIC_SUCCESS_NUM          1213
#define IDC_BUTTON_UPDATA_INSTRUMENTLIST 1214
#define IDC_BUTTON_READ_EEPROM          1215
#define IDC_CHECK_CONTINUEWORK          1216
#define IDC_EDIT_AIMPORT                1217
#define IDC_IPADDRESS_AIM               1218
#define IDC_STATIC_GRAPH                1219
#define IDC_HSCROLLBAR                  1220
#define IDC_EDIT_HP                     1221
#define IDC_EDIT_READ_TIMER             1222
#define IDC_EDIT2                       1223
#define IDC_EDIT_WRITE_TIMER            1223

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1223
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
