//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Operation.rc
//
#define IDCANCEL2                       3
#define ID_BTNEND                       3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_ACTIVESOURCEVIEW            103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_OperationTYPE               129
#define IDB_TOOLBAR256                  130
#define IDR_POPUP_TOOLBAR               131
#define IDD_STATUSMAILVIE               132
#define IDR_POPUP_VPSHOT                133
#define IDB_BITMAP1                     135
#define IDB_BITMAPVPSTATE               135
#define E                               136
#define IDB_SOURCESTATE                 136
#define IDD_SOURCESETUPDLG              137
#define IDD_SOURCEEXPLODLG              138
#define IDD_SOURCEVIBRODLG              139
#define IDD_SHOTSETUPDLG                141
#define IDD_COMMENTTYPESETUPDLG         142
#define IDD_DELAYSETUPDLG               143
#define IDD_PROCESSTYPEDLG              144
#define IDD_PROCESSIMPULSIVEDLG         146
#define IDD_RESULTSOFACKEDVP            147
#define IDR_SETUPBAR                    148
#define IDR_VIEWWNDBAR                  150
#define IDB_VIEWBAR256                  152
#define IDB_SETUPBAR256                 153
#define IDR_POPUP_ACTIVESOURCE          154
#define IDD_ASSOCIATEVPDLG              155
#define IDD_ASSOCIATESPLSPNDLG          156
#define IDB_BLASTERRED                  157
#define IDD_ACTIVESOURCECONTROL         158
#define IDR                             161
#define IDC_BUTTONGO                    1002
#define IDC_BUTTONSTOP                  1003
#define IDC_BUTTONABORT                 1004
#define IDC_LISTSTATUSMAIL              1006
#define IDC_STATICSTATUSMAIL            1007
#define IDC_BTNAPPLY                    1008
#define IDC_BTNRESET                    1009
#define IDC_STATICTAB                   1010
#define IDC_BTNADD                      1019
#define IDC_BTNCHANGE                   1020
#define IDC_BTNDELETE                   1021
#define IDC_STATICGRID                  1031
#define IDC_STATICGRIDEDIT              1032
#define IDC_STATICGRIDLIST              1033
#define ID_BTNAPPLY                     1035
#define ID_BTNRESET                     1036
#define ID_BTNADD                       1037
#define ID_BTNCHANGE                    1038
#define ID_BTNDELETE                    1039
#define ID_BTNREVERSE                   1040
#define IDC_EDITCOMMENT                 1040
#define IDC_EDITENDOFACQ                1041
#define IDC_SLIDERENDOFACQ              1042
#define IDC_EDITENDOFVP                 1043
#define IDC_SLIDERENDOFVP               1044
#define IDC_RADIOSTAND                  1047
#define IDC_RADIOADVANCE                1048
#define IDC_EDITFDUSN                   1049
#define IDC_EDITRECORDLEN               1050
#define IDC_EDITREFRACTION              1051
#define IDC_EDITTBWINDOW                1052
#define IDC_STATICAUXACQ                1053
#define IDC_COMBOPROCESSTYPE            1054
#define IDC_STATICTBWINDOW              1055
#define IDC_STATICREFRACTION            1056
#define IDC_STATICRECORDLEN             1057
#define IDC_STATICRESULT                1059
#define IDC_LISTRESULT                  1060
#define IDC_EDITSHOTNUMBER              1061
#define IDC_EDITSFL                     1062
#define IDC_EDITSFN                     1063
#define IDC_STATICBLASTER               1063
#define IDC_STATICIMAGE                 1064
#define IDC_STATICUPHOLEMS              1065
#define IDC_EDITUPHOLE                  1066
#define IDC_STATICTBMS                  1067
#define IDC_EDITTBMS                    1068
#define ID_VIEW_APPLOOK_2000            32771
#define ID_VIEW_APPLOOK_XP              32772
#define ID_VIEW_APPLOOK_2003            32773
#define ID_VIEW_APPLOOK_VS2005          32774
#define ID_VIEW_APPLOOK_2007_1          32775
#define ID_VIEW_APPLOOK_2007_2          32776
#define ID_VIEW_APPLOOK_2007_3          32777
#define ID_VIEW_APPLOOK_2007_4          32778
#define ID_VIEW_APPLOOK_WIN_XP          32779
#define ID_VIEW_APPLOOK_VS2008          32780
#define ID_VIEW_APPLOOK_CARBON          32781
#define ID_VIEW_WORKSPACE               32782
#define ID_Menu                         32783
#define ID_VIEW_CUSTOMIZE               32784
#define ID_VIEW_TOOLBARS                32785
#define ID_32786                        32786
#define ID_VIEW_ACTIVESOURCE            32787
#define ID_32788                        32788
#define ID_VIEW_ALLVP                   32789
#define ID_VIEW_ACTIVEACQ               32790
#define ID_Menu32791                    32791
#define ID_VIEW_ALLTODO                 32792
#define ID_32793                        32793
#define ID_VIEW_ALLDONE                 32794
#define ID_SETUP_SOURCE                 32795
#define ID_SETUP_OPERATION              32796
#define ID_SETUP_PROCESSTYPE            32797
#define ID_SETUP_NOISEEDITING           32798
#define ID_SETUP_COMMENTS               32799
#define ID_SETUP_OPTIONS                32800
#define ID_SETUP_DELAYSTEUP             32801
#define ID_SETUP_PREFERENCES            32802
#define ID_VIEW_OPERATIONREPORT         32803
#define IDC_VPSHOT_SELECTED             32804
#define ID_VPSHOT_SELECTED              32805
#define ID_VPSHOT_ONE                   32806
#define ID_VPSHOT_TWO                   32807
#define ID_VPSHOT_THREE                 32808
#define ID_VPSHOT_FOUR                  32809
#define ID_VPSHOT_FIVE                  32810
#define ID_VPSHOT_SIX                   32811
#define ID_VPSHOT_SENVEN                32812
#define ID_VPSHOT_EIGHT                 32813
#define ID_VPSHOT_NINE                  32814
#define ID_VPSHOT_TEN                   32815
#define ID_VPTODOSHOT_ONE               32816
#define ID_VPTODOSHOT_TWO               32817
#define ID_VPTODOSHOT_THREE             32818
#define ID_VPTODOSHOT_FOUR              32819
#define ID_VPTODOSHOT_FIVE              32820
#define ID_VPTODOSHOT_SIX               32821
#define ID_ACTIVESOURCE_SOURCE          32821
#define ID_VPTODOSHOT_SENVEN            32822
#define ID_ACTIVESOURCE_DISASSOCIATEVP  32822
#define ID_VPTODOSHOT_EIGHT             32823
#define ID_ACTIVESOURCE_ASSOCIATEVP     32823
#define ID_VPTODOSHOT_NINE              32824
#define ID_ACTIVESOURCE_ASSOCIATESPLSPN 32824
#define ID_VPTODOSHOT_TEN               32825
#define ID_ACTIVESOURCE_CLEANREADY      32825
#define ID_VPDONESHOT_ONE               32826
#define ID_VPDONESHOT_TWO               32827
#define ID_VPDONESHOT_THREE             32828
#define ID_VPDONESHOT_FOUR              32829
#define ID_VPDONESHOT_FIVE              32830
#define ID_VPDONESHOT_SIX               32831
#define ID_VPDONESHOT_SENVEN            32832
#define ID_VPDONESHOT_EIGHT             32833
#define ID_VPDONESHOT_NINE              32834
#define ID_VPDONESHOT_TEN               32835

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         32826
#define _APS_NEXT_CONTROL_VALUE         1067
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
