//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BCGPVisualStudioGUIDemo.rc
//
#define IDC_GRID_EDIT                   1
#define IDC_GRID_LIST_LBBUTTONDOWN      1
#define IDC_GRID_LIST                   2
#define IDC_GRID_LIST_DBLCLK            2
#define IDC_APPLY                       3
#define IDC_EDIT_AUXILIARYDESCR         11
#define IDC_EDIT_ABSOLUTESPREAD         12
#define IDC_EDIT_DELAYBETWEENTEST       13
#define IDC_EDIT_RECORDLENGTH           14
#define IDC_EDIT_TESTFILENB             15
#define IDC_CHECK_RECORDRESULTS         16
#define IDP_OLE_INIT_FAILED             100
#define IDS_MAIN_TOOLBAR                101
#define IDS_STRING_NOT_FOUND_FMT        102
#define IDS_BUILD_TOOLBAR               103
#define IDS_RESOURCE_TOOLBAR            104
#define ID_VIEW_TOOLBOX                 105
#define IDS_EDIT_TOOLBAR                106
#define IDS_CARET_POS                   107
#define ID_EDIT_FINDNEXT                108
#define IDP_SOCKETS_INIT_FAILED         108
#define ID_VIEW_FIELD_TOOLBAR           109
#define ID_VIEW_EDITCTRL                112
#define ID_EDIT_FINDPREV                113
#define ID_EDIT_SHOWHINT                116
#define IDS_EDITFAILED                  121
#define IDS_PGUPFAILED                  122
#define IDR_MAINFRAME                   128
#define IDR_BCGDEVTYPE0                 129
#define IDR_BCGDEVTYPE_CPP              130
#define IDR_BCGDEVTYPE_WEB              131
#define IDR_CONTEXT_MENU                132
#define IDI_CLASS_VIEW                  132
#define IDR_POPUP_TOOLBAR               133
#define IDI_RES_VIEW                    133
#define IDI_FILE_VIEW                   134
#define IDB_CLASS_VIEW                  135
#define IDI_OUTPUT_BAR                  135
#define IDB_RESOURCE_VIEW               136
#define IDI_WATCH_BAR                   136
#define IDB_FILE_VIEW                   137
#define IDR_POPUP_SORT                  139
#define IDB_LOGO                        141
#define IDR_MENU_IMAGES                 142
#define IDR_POPUP_OUTPUT                144
#define IDR_POPUP_MAIN_AREA             146
#define IDR_MENU_DIRS                   147
#define IDI_DYNAMIC_HELP_VIEW           148
#define IDB_DYNAMIC_HELP_VIEW           150
#define IDI_PROPERTIES_BAR              153
#define IDR_EDIT                        155
#define IDB_START                       156
#define IDI_TOOLBOX_BAR                 157
#define IDI_CLASS_VIEW_HC               158
#define IDR_MENU_ARGS                   161
#define IDR_POPUP_SOLUTION              162
#define IDR_POPUP_RESOURCE              163
#define IDR_POPUP_CONTROLBAR            164
#define IDB_TOOLS_PAGE1                 168
#define IDB_TOOLS_PAGE2                 169
#define IDB_TOOLS_PAGE3                 170
#define IDB_IMG_INTELLISENSE            173
#define IDB_OPTIONSIMAGES               174
#define IDR_POPUP_SELECTIONMARGIN       176
#define ID_EXAMPLE_CPP                  177
#define IDR_POPUP_MDITABS               177
#define ID_EXAMPLE_WEB                  178
#define IDR_POPUP_DROP_MDITABS          178
#define IDD_APP_LOOK                    180
#define IDR_EDITOR_XML_SETTINGS_WEB     182
#define IDR_EDITOR_XML_SETTINGS_CPP     183
#define IDB_MENU_IMAGES_HC              185
#define IDB_MAINFRAME_HC                186
#define IDB_BUILD_HC                    187
#define IDB_EDIT_HC                     188
#define IDI_FILE_VIEW_HC                189
#define IDB_IMG_INTELLISENSE_HC         189
#define IDI_RES_VIEW_HC                 190
#define IDI_TOOLBOX_BAR_HC              191
#define IDI_PROPERTIES_BAR_HC           192
#define IDI_DYNAMIC_HELP_VIEW_HC        193
#define IDI_WATCH_BAR_HC                194
#define IDI_OUTPUT_BAR_HC               195
#define IDB_SOLUTION_EXPLORER_HC        195
#define IDB_PROPERTIES_HC               196
#define IDB_CLASS_VIEW_HC               197
#define IDB_SORT_HC                     198
#define IDB_START_HC                    199
#define IDB_TOOLS_PAGE1_HC              200
#define IDB_TOOLS_PAGE2_HC              201
#define IDB_TOOLS_PAGE3_HC              202
#define IDB_FILE_VIEW_HC                203
#define IDB_DYNAMIC_HELP_HC             204
#define IDB_DYNAMIC_HELP_VIEW_HC        205
#define IDB_RESOURCE_VIEW_HC            206
#define IDB_BREAK                       207
#define IDB_CURRENT                     208
#define IDB_TOOLBAR_RESOURCE_HC         209
#define IDB_START_HC_2010               210
#define IDR_TOOLBAR_MATRIX_INSTRUMENT_GRAPH_TOP 211
#define IDR_TOOLBAR_MATRIX_GRAPH_BOTTOM 213
#define IDR_TOOLBAR_MATRIX_SENSOR_GRAPH_TOP 214
#define IDD_DIALOG_SURVEYSETUP          215
#define IDD_DIALOG_LAYOUTSETUP          216
#define IDD_DIALOG_LOOKSETUP            217
#define IDD_DIALOG_FORMLINESETUP        218
#define IDD_DIALOG_TESTBASESETUP        219
#define IDD_DIALOG_SPREADSETUP1         220
#define IDD_DIALOG_SPREADSETUP          220
#define IDD_DIALOG_TESTSETUP1           221
#define IDD_DIALOG_TESTSETUP            221
#define IDR_POPUP_GRAPHVIEW_INSTRUMENT  222
#define IDB_BITMAP_GO                   240
#define IDB_BITMAP_LOOK                 241
#define IDR_TOOLBAR_MATRIX_FIELD        242
#define ID_VIEW_MATRIX_FIELD_TOOLBAR    244
#define IDB_PNG1                        247
#define IDB_TOOLBAR_MATRIX_FIELD_HC     247
#define IDR_TOOLBAR_MATRIX_SETUP        256
#define IDR_TOOLBAR_MATRIX_VIEW         258
#define IDR_TOOLBAR_MATRIX_SEISMONITOR_GRAPH_TOP 259
#define IDR_MENU_MATRIX_VIEW_GRAPH      260
#define IDR_MENU_MATRIX_VIEW_LIST       261
#define IDR_POPUP_GRAPHVIEW_SENSOR      262
#define IDR_TOOLBAR2                    264
#define IDD_DIALOG_SELECTSHOTPOINT      267
#define IDD_DIALOG_SETINSTRUMENT        268
#define IDC_MAIL                        1000
#define IDC_URL                         1001
#define IDC_VERSION                     1002
#define IDC_APP_LOOK1                   1012
#define IDC_APP_LOOK2                   1013
#define IDC_APP_LOOK3                   1014
#define IDC_SHOW_AT_STARTUP             1015
#define IDC_ONENOTE_TABS                1016
#define IDC_DOCK_TAB_COLORS             1017
#define IDC_XP_COLORS                   1018
#define IDC_APP_LOOK4                   1018
#define IDC_ACTIVETAB_CLOSE_BUTTON      1018
#define IDC_APP_LOOK5                   1019
#define IDC_ROUNDED_TABS                1020
#define IDC_CUSTOM_TOOLTIPS             1021
#define IDC_APP_LOOK6                   1022
#define IDC_APP_LOOK                    1023
#define IDC_STYLE                       1024
#define IDC_BUTTON_APPLYALL             1025
#define IDC_BUTTON_APPLYSENSOR          1026
#define IDC_BUTTON_RESET                1027
#define IDC_BUTTON_ADD                  1028
#define IDC_BUTTON_CHANGE               1029
#define IDC_BUTTON_DELETE               1030
#define IDC_BUTTON7                     1031
#define IDC_BUTTON_REVERSE              1031
#define IDC_STATIC_TAB                  1032
#define IDC_BUTTON_APPLY                1033
#define IDC_BUTTON_CLEAR                1034
#define IDC_BUTTON2                     1035
#define IDC_CANCEL                      1035
#define IDC_BUTTON_ADD_NEXT             1035
#define IDC_CHECK_LOOKAUTO              1036
#define IDC_CHECK_RESISTANCE            1037
#define IDC_CHECK_TILT                  1038
#define IDC_CHECK_LEAKAGE               1039
#define IDC_BUTTON_GO                   1040
#define IDC_BUTTON_SELECTSHOTPOINT      1042
#define IDC_BUTTON1                     1043
#define IDC_OK                          1043
#define IDC_BUTTON_ADD_PREVIOUS         1043
#define IDC_COMBO_INSTRUMENT_TYPE       1044
#define IDC_BUTTON4                     1046
#define ID_VIEW_CUSTOMIZE               32770
#define ID_VIEW_USER_TOOLBAR1           32771
#define ID_VIEW_USER_TOOLBAR2           32772
#define ID_VIEW_USER_TOOLBAR3           32773
#define ID_VIEW_USER_TOOLBAR4           32774
#define ID_VIEW_USER_TOOLBAR5           32775
#define ID_VIEW_USER_TOOLBAR6           32776
#define ID_VIEW_USER_TOOLBAR7           32777
#define ID_VIEW_USER_TOOLBAR8           32778
#define ID_VIEW_USER_TOOLBAR9           32779
#define ID_VIEW_USER_TOOLBAR10          32780
#define ID_VIEW_TOOLBARS                32781
#define ID_VIEW_WORKSPACE               32782
#define ID_VIEW_OUTPUT                  32783
#define ID_WINDOW_MANAGER               32784
#define ID_VIEW_DYNAMICHELP             32785
#define ID_DUMMY_COMPILE                32787
#define ID_DUMMY_BUILD                  32788
#define ID_DUMMY_STOP_BUILD             32789
#define ID_DUMMY_EXECUTE                32790
#define ID_DUMMY_GO                     32791
#define ID_DUMMY_SELECT_ACTIVE_CONFIGURATION 32794
#define ID_DUMMY_REMOVE_ALL_BREAKPOINTS 32796
#define ID_VIEW_BUILD_TOOLBAR           32797
#define ID_DUMMY_REBUILD_ALL            32798
#define ID_DUMMY_CLEAN                  32799
#define IDS_DUMMY_UNDO_ACTION           32800
#define ID_VIEW_CB_CAPTION              32804
#define ID_VIEW_FORCE_GRADIENT          32805
#define ID_USER_TOOL1                   32806
#define ID_USER_TOOL2                   32807
#define ID_USER_TOOL3                   32808
#define ID_USER_TOOL4                   32809
#define ID_USER_TOOL5                   32810
#define ID_USER_TOOL6                   32811
#define ID_USER_TOOL7                   32812
#define ID_USER_TOOL8                   32813
#define ID_USER_TOOL9                   32814
#define ID_USER_TOOL10                  32815
#define ID_TOOLS_MACRO                  32816
#define ID_TOOLS_ENTRY                  32819
#define ID_NEW_DIALOG                   32823
#define ID_NEW_MENU                     32824
#define ID_NEW_CURSOR                   32825
#define ID_NEW_ICON                     32826
#define ID_NEW_BITMAP                   32827
#define ID_NEW_TOOLBAR                  32828
#define ID_NEW_ACCELERATOR              32829
#define ID_NEW_STRING_TABLE             32830
#define ID_NEW_VERSION                  32831
#define ID_OUTPUT_GOTO_ERROR            32833
#define ID_CLASS_DEFINITION             32836
#define ID_CLASS_ADD_MEMEBER_FUNCTION   32837
#define ID_CLASS_ADD_MEMEBER_VARIABLE   32838
#define ID_CLASS_PROPERTIES             32839
#define ID_RESOURCE_OPEN                32840
#define ID_RESOURCE_OPEN_BINARY         32841
#define ID_DUMMY_INSERT_RESOURCE        32842
#define ID_VIEW_TAB_FLAT_BORDERS        32844
#define ID_HELP_KEYBOARDMAP             32845
#define ID_VIEW_DOCUMENT_TAB            32845
#define ID_MENU_DIR1                    32847
#define ID_MENU_DIR2                    32848
#define ID_MENU_DIR3                    32849
#define ID_MDITABS_ICONS                32850
#define ID_MDITABS_TOP                  32851
#define ID_MDITABS_BOTTOM               32852
#define ID_VIEW_MDI_TABS                32853
#define ID_MDITABS_CLOSE                32855
#define ID_VIEW_CLASS                   32856
#define ID_VIEW_RESOURCE                32857
#define ID_VIEW_FILE                    32858
#define ID_MENU_ITEM1                   32866
#define ID_MENU_ITEM2                   32867
#define ID_MENU_ITEM3                   32868
#define ID_SORTING_GROUPBYTYPE          32869
#define ID_SORTING_SORTALF              32870
#define ID_SORTING_SORTBYTYPE           32871
#define ID_SORTING_SORTBYACCESS         32872
#define ID_DHELP1                       32873
#define ID_DHELP2                       32874
#define ID_DHELP3                       32875
#define ID_EXPAND                       32878
#define ID_SORTINGPROP                  32879
#define ID_PROPERIES1                   32880
#define ID_PROPERIES2                   32881
#define ID_NEW_FOLDER                   32882
#define ID_PROPERTIES                   32883
#define ID_SOLUTION_OPEN                32884
#define ID_SOLUTION_OPEN_WITH           32885
#define ID_FILE_NEW_PROJECT             32886
#define ID_FILE_NEW_BLANK_SOLUTION      32887
#define ID_FILE_OPEN_SOLUTION           32888
#define ID_FILE_CLOSE_SOLUTION          32889
#define ID_FILE_SAVE_ALL                32892
#define ID_TOOLS_DEBUG_PROCESSES        32893
#define ID_TOOLS_CONNECT_TO_DATABASE    32894
#define ID_WINDOW_CLOSE_ALL             32895
#define ID_HELP_SHOW_START              32896
#define ID_VIEW_REFRESH                 32897
#define ID_VIEW_PROPERTIES              32900
#define ID_VIEW_WATCH                   32901
#define ID_VIEW_FULLSCREEN              32902
#define ID_EDIT_TOGGLEBOOKMARK          32925
#define ID_EDIT_NEXTBOOKMARK            32926
#define ID_EDIT_PREVIOUSBOOKMARK        32927
#define ID_EDIT_TOGGLEBREAKPOINT        32928
#define ID_EDIT_CLEAR_ALLBOOKMARKS      32930
#define ID_EDIT_INCREASE_IDENT          32931
#define ID_EDIT_DECREASE_IDENT          32932
#define ID_VIEW_EDIT_TOOLBAR            32933
#define ID_EDIT_LISTMEMBERS             32935
#define IDS_UAT_UNDEFINED               32936
#define IDS_UAT_INSERTDATA              32937
#define IDS_UAT_TYPING                  32937
#define IDS_UAT_DELETEDATA              32938
#define IDS_UAT_DELETE                  32938
#define IDS_UAT_INDENTDATA              32939
#define IDS_UAT_INDENT                  32939
#define IDS_UAT_UNKNOWN                 32940
#define IDS_UAT_CUT                     32941
#define IDS_UAT_PASTE                   32942
#define IDS_UAT_BACKSPACE               32943
#define IDS_UAT_UNINDENT                32944
#define IDS_UAT_DRAGDROP                32945
#define IDS_UAT_TAB                     32946
#define IDS_UAT_ENTER                   32947
#define ID_EDIT_FIND_COMBO              32948
#define ID_TOOLS_OPTIONS                32949
#define ID_VIEW_APP_LOOK                32950
#define ID_HELP_WEB                     32951
#define ID_EDIT_HIDESELECTION           32952
#define ID_EDIT_TOGGLEOUTLINING         32953
#define ID_EDIT_STOPHIDINGCURRENT       32954
#define ID_EDIT_TOGGLEALLOUTLINING      32955
#define ID_EDIT_COLLAPSETODEFINITIONS   32956
#define ID_EDIT_STOPOUTLINING           32957
#define ID_EDIT_AUTOOUTLINING           32958
#define ID_EDIT_ENABLEOUTLINING         32959
#define ID_EDIT_NEXT_WORD               32960
#define ID_EDIT_LINENUMBERS             32961
#define IDS_UAT_REPLACE                 32962
#define ID_EDIT_GOTO_LINE               32963
#define ID_MDI_NEW_VERT_GROUP           32965
#define ID_MDI_NEW_HORZ_TAB_GROUP       32966
#define ID_MDI_MOVE_TO_PREV_GROUP       32967
#define ID_MDI_CANCEL                   32968
#define ID_MDI_MOVE_TO_NEXT_GROUP       32969
#define ID_TOOLBOX                      32970
#define ID_MDI_TABBED_DOCUMENT          32974
#define ID_VIEW_SENSORLIST              32975
#define ID_MATRIX_SENSORLIST            32976
#define ID_MATRIX_INSTRUMENTLISTVIEW    32977
#define ID_MATRIX_INSTRUMENTLIST        32978
#define ID_MATRIX_SENSORGRAPH           32981
#define ID_MATRIX_INSTRUMENTGRAPH       32982
#define ID_BUTTON_MATRIX_INSTRUMENT_GRAPH_POINT 32983
#define ID_BUTTON_MATRIX_INSTRUMENT_GRAPH_LINE 32984
#define ID_BUTTON_MATRIX_INSTRUMENT_GRAPH_CROSS 32985
#define ID_BUTTON_MATRIX_INSTRUMENT_GRAPH_POWER 32988
#define ID_BUTTON_MATRIX_INSTRUMENT_GRAPH_COLLECT 32989
#define ID_BUTTON_MATRIX_GRAPH_ZOOMIN   32992
#define ID_BUTTON_MATRIX_GRAPH_ZOOMOUT  32994
#define ID_BUTTON_MATRIX_GRAPH_LINENAMELABEL 32995
#define ID_BUTTON_MATRIX_GRAPH_LINENAME 32996
#define ID_BUTTON_MATRIX_GRAPH_POINTNBLABEL 32997
#define ID_BUTTON_MATRIX_GRAPH_POINTNB  32998
#define ID_MATRIX_SURVEYSETUP           33000
#define ID_MATRIX_LAYOUTSETUP           33001
#define ID_MATRIXSETUP_LOOKSETUP        33002
#define ID_MATRIX_LOOKSETUP             33003
#define ID_MATRIXSETUP_FORMLINESETUP    33004
#define ID_MATRIX_FORMLINESETUP         33005
#define ID_MATRIXSETUP_TESTBASESETUP    33006
#define ID_MATRIX_TESTBASESETUP         33007
#define ID_MATRIX_TESTSETUP             33008
#define IDR_POPUP_GRAPHVIEW_INSTRUMENT_SETMARKER 33009
#define ID_DUMMY_PROPERTIES             33010
#define IDR_POPUP_GRAPHVIEW_INSTRUMENT_PROPERTIES 33011
#define ID_DUMMY_SETAUXILIARYS          33012
#define IDR_POPUP_GRAPHVIEW_INSTRUMENT_SETAUXILIARYS 33013
#define ID_DUMMY_SETLOWBOXOFDETOUR      33014
#define ID_DUMMY_SETHIGHBOXOFDETOUR     33015
#define ID_DUMMY_FORMLINE               33016
#define IDR_POPUP_GRAPHVIEW_INSTRUMENT_FORMLINE 33017
#define IDR_POPUP_GRAPHVIEW_INSTRUMENT_SETHIGHBOXOFDETOUR 33018
#define IDR_POPUP_GRAPHVIEW_INSTRUMENT_SETLOWBOXOFDETOUR 33019
#define IDR_POPUP_GRAPHVIEW_INSTRUMENT_SETAUXILIARY 33020
#define ID_EMPTY                        33021
#define ID_BUTTON_MATRIX_INSTRUMENT_GRAPH_TESTMARKER 33022
#define ID_BUTTON_MATRIX_INSTRUMENT_GRAPH_QCLABEL 33023
#define ID_BUTTON_MATRIX_INSTRUMENT_GRAPH_QCLIST 33024
#define ID_BUTTON33025                  33025
#define ID_BUTTON_MATRIX_INSTRUMENT_GRAPH_QCGO 33025
#define ID_BUTTON_MATRIX_INSTRUMENT_GRAPH_LOOK 33026
#define ID_BUTTON_MATRIX_SENSOR_GRAPH_TESTMARKER 33028
#define ID_BUTTON_MATRIX_SENSOR_GRAPH_SENSORQCTYPELABEL 33029
#define ID_BUTTON_MATRIX_SENSOR_GRAPH_SENSORQCTYPELIST 33030
#define ID_BUTTON_MATRIX_SENSOR_GRAPH_LOOK 33031
#define ID_BUTTON_MATRIX_SENSOR_GRAPH_QCGO 33032
#define ID_BUTTON_MATRIX_SENSOR_GRAPH_QCLIST 33033
#define ID_BUTTON_MATRIX_SENSOR_GRAPH_QCLABEL 33034
#define ID_BUTTON33035                  33035
#define ID_BUTTON_MATRIX_FIELD_ON       33036
#define ID_BUTTON_MATRIX_FIELD_OFF      33037
#define ID_VIEW_MATRIXFIELDVIEW         33038
#define ID_VIEW_MATRIX_FIELDVIEW_TOOLBAR 33039
#define ID_BUTTON33040                  33040
#define ID_MATRIXVIEW_TOPVIEW           33041
#define ID_MATRIXVIEW_INSTRNUMVIEW      33042
#define ID_BUTTON_MATRIX_FIELD_ON_LABEL 33043
#define ID_BUTTON_MATRIX_FIELD_OFF_LABEL 33044
#define ID_BUTTON33046                  33046
#define ID_BUTTON_MATRIX_FIELD_OFF_GRAPH_GRAPH 33046
#define ID_BUTTON_MATRIX_FIELD_OFF_GRAPH 33047
#define ID_BUTTON_MATRIX_FIELD_ON_GRAPH 33048
#define ID_MATRIX_VIEWGRAPH             33049
#define ID_MATRIX_VIEWLIST              33050
#define ID_SETUP_SPREADTYPE             33051
#define ID_MATRIX_SPREADSETUP           33052
#define ID_MATRIX_SEISMONITORGRAPH      33054
#define ID_BUTTON_MATRIX_SEISMONITOR_GRAPH_TESTMARKER 33055
#define ID_BUTTON_MATRIX_SEISMONITOR_GRAPH_SEISMONITOR 33056
#define ID_BUTTON_MATRIX_SEISMONITOR_GRAPH_SENSORQCTYPELIST 33057
#define ID_BUTTON_MATRIX_SEISMONITOR_GRAPH_SENSORQCTYPELABEL 33058
#define ID_BUTTON_MATRIX_SEISMONITOR_GRAPH_LIMIT 33059
#define ID_BUTTON_MATRIX_SEISMONITOR_GRAPH_LIMITLABEL 33060
#define ID_BUTTON_MATRIX_SEISMONITOR_GRAPH_LIMITVALUE 33061
#define IDR_POPUP_GRAPHVIEW_SENSOR_PROPERTIES 33062
#define IDR_POPUP_GRAPHVIEW_SENSOR_SETAUXILIARY 33063
#define IDR_POPUP_GRAPHVIEW_SENSOR_SETLOWBOXOFDETOUR 33064
#define IDR_POPUP_GRAPHVIEW_SENSOR_SETHIGHBOXOFDETOUR 33065
#define IDR_POPUP_GRAPHVIEW_SENSOR_MUTE 33066
#define ID_BUTTON_MATRIX_SEISMONITOR_GRAPH_SEISMONITORLABEL 33067
#define IDR_POPUP_GRAPHVIEW_INSTRUMENT_SETINSTRUMENT 33068
#define ID_BUTTON_MATRIX_SENSOR_GRAPH_NBSTART 40000
#define IDR_BCGDEVTYPE_SENSORLIST       56789
#define ID_VIEW_SETUP_TOOLBAR           61446
#define ID_VIEW_VIEW_TOOLBAR            61447

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        270
#define _APS_NEXT_COMMAND_VALUE         33069
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           123
#endif
#endif
