//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by pcid.rc
//
#define IDC_MYICON                      2
#define IDD_PCID_DIALOG                 102
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDS_START                       104
#define IDS_END                         105
#define IDS_TRANSFER_P2N_ERROR          106
#define IDI_PCID                        107
#define IDT_TIMER                       107
#define IDI_SMALL                       108
#define IDS_LISTEN_PORT                 108
#define IDC_PCID                        109
#define IDS_INPUT_BUFFERS_NUM           110
#define IDS_INPUT_BUFFER_SIZE           111
#define IDS_INPUT_WAITING_TIME          112
#define IDS_RECV_BUFFER_SIZE            113
#define IDS_SEND_BUFFER_SIZE            114
#define IDS_REMOTE_IP                   115
#define IDS_LOG_IP                      116
#define IDS_REMOTE_PORT                 117
#define IDS_RECV_WAITING_TIME           118
#define IDS_LOG_PORT                    119
#define IDS_PRODUCT_INFORMATION_STRING  120
#define IDS_LISTEN_PORT_STRING          121
#define IDS_REMOTE_IP_STRING            122
#define IDS_REMOTE_PORT_STRING          123
#define IDS_RECV_BUFFER_SIZE_STRING     124
#define IDS_SEND_BUFFER_SIZE_STRING     125
#define IDS_RECV_THREAD_WAITING_TIME_STRING 126
#define IDS_INPUT_WAITING_TIME_STRING   127
#define IDR_MAINFRAME                   128
#define IDS_INPUT_BUFFER_SIZE_STRING    128
#define IDS_INPUT_BUFFERS_NUM_STRING    129
#define IDS_LOG_PORT_STRING             130
#define IDS_LOG_IP_STRING               131
#define IDD_OPTIONS_DIALOG              131
#define IDS_PARALLEL_REGISTER_ERROR     132
#define IDD_INPUT_DIALOG                132
#define IDS_PARALLEL_INPUT_ARG_ERROR    133
#define IDS_PARALLEL_ONPUT_ARG_ERROR    134
#define IDS_PARALLEL_MULTI_BUF_SET_ERROR 135
#define IDS_PARALLEL_START_ERROR        136
#define IDS_PARALLEL_CLEAR_ERROR        137
#define IDS_PARALLEL_GET_NEXT_READY_ERROR 138
#define IDS_PARALLEL_RETURN_BUF_ID_ERROR 139
#define IDS_STRING140                   140
#define IDS_STRING141                   141
#define IDS_STRING142                   142
#define IDS_STRING143                   143
#define IDS_STRING144                   144
#define IDS_STRING145                   145
#define IDS_IP_PORT_FILTER              146
#define IDS_STRING147                   147
#define IDS_STRING148                   148
#define IDS_STRING149                   149
#define IDS_STRING150                   150
#define IDS_STRING151                   151
#define IDS_STRING152                   152
#define IDS_STRING153                   153
#define IDS_ENABLE_TO_CHECK_CRC         154
#define IDS_DISABLE_TO_CHECK_CRC        155
#define IDS_STRING156                   156
#define IDS_STRING157                   157
#define IDS_STRING158                   158
#define IDS_ENABLE_TO_TRANSFER_DATA     159
#define IDS_DISABLE_TO_TRANSFER_DATA    160
#define IDS_STRING161                   161
#define IDS_OUTPUT_BUFFER_SIZE          162
#define IDS_OUTPUT_BUFFER_SIZE_STRING   163
#define IDS_STRING164                   164
#define IDS_STRING165                   165
#define IDS_STRING166                   166
#define IDS_IGNORED_PORT_STRING         167
#define IDS_IGNORED_PORT                168
#define IDS_BE_ALL_INFO_OUTPUTTED_STRING 169
#define IDS_BE_ALL_INFO_OUTPUTTED       170
#define IDC_STATIC_PCI_INPUT_NUM        1004
#define IDC_STATIC_PCI_OUTPUT_NUM       1005
#define IDC_STATIC_UDP_RECV_NUM         1006
#define IDC_STATIC_UDP_SEND_NUM         1007
#define IDC_BUTTON2                     1046
#define IDC_BUTTON_MODIFY_IP            1046
#define IDC_BUTTON3                     1047
#define IDC_BUTTON_DELETE_IP            1047
#define IDC_OPTIONS_BUTTON_OK           1048
#define IDC_OPTIONS_BUTTON_CANCEL       1049
#define IDC_IP_LIST                     1050
#define IDC_EDIT1                       1050
#define IDC_INPUT_EDIT                  1050
#define IDC_TRANSFER_DATA_CHECK         1051
#define IDC_ALL_LOG_OUTPUT_CHECK        1052
#define IDC_BUTTON9                     1054
#define IDC_BUTTON_ADD_IP               1054
#define IDC_BUTTON6                     1058
#define IDC_BUTTON_MODIFY_PORT          1058
#define IDC_BUTTON7                     1059
#define IDC_BUTTON_DELETE_PORT          1059
#define IDC_PORT_LIST                   1060
#define IDC_BUTTON10                    1061
#define IDC_BUTTON_ADD_PORT             1061
#define IDC_BTN_DI                      1103
#define IDC_ASSIGN_IP_PORT_BUTTON       1104
#define IDC_CRC_CHECK                   1105
#define IDC_BTN_SAVEDATA                1106
#define IDC_BTN_SEND_ONE_FRAME          1107
#define IDC_EDIT_LISTEN_PORT            1108
#define IDC_EDIT_PORT                   1109
#define IDC_EDIT_SAVE_PORT              1110
#define IDC_EDIT_REMOTE_IP              1111
#define IDC_EDIT_REMOTE_PORT            1112
#define IDC_EDIT_LOG_PORT               1113
#define IDC_EDIT_LOG_IP                 1114
#define IDC_EDIT_PCI_BUFFER_NUM         1115
#define IDC_EDIT_PCI_BUFFER_SIZE        1116
#define IDC_EDIT_PCI_POLL_TIME          1117
#define IDC_EDIT_SOCK_RECV_NUM          1118
#define IDC_EDIT_SOCK_SEND_NUM          1119
#define IDC_EDIT_SOCK_POLL_TIME         1120
#define IDC_EDIT_PCI_WRITE_BUFFER_SIZE  1121
#define IDC__IGNORE_LOG_PORT            1122
#define IDC_KEY_BUTTON                  1503
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
