//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Operation.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_MAIN_TOOLBAR                101
#define IDS_SETUP_TOOLBAR               102
#define IDS_VIEW_TOOLBAR                103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_OperationTYPE               129
#define IDR_POPUP_TOOLBAR               131
#define IDB_TOOLBAR256                  150
#define IDB_BITMAP_VPVIEW256            151
#define IDD_ACTIVESOURCEVIEW            160
#define IDI_ICON_RED                    161
#define IDI_ICON_GREEN                  162
#define IDI_ICON_ORANGE                 163
#define IDR_POPUP_ACTIVESOURCE          164
#define IDR_POPUP_VPSHOT                165
#define IDB_BITMAP_ACTIVESOURCE         167
#define IDB_BITMAP_VP                   168
#define IDB_SERVER_CONNECTED            170
#define IDB_SERVER_DISCONNECTED         171
#define IDR_SETUPBAR                    173
#define IDB_BITMAP_SETUPBAR256          175
#define IDB_BITMAP_VIEWBAR256           176
#define IDR_VIEWBAR                     177
#define IDR_POPUP_VPVIEW                182
#define IDR_VPVIEWBAR                   190
#define IDB_BITMAP_ACQ                  195
#define IDD_DIALOG_SOURCESETUP          196
#define IDD_DIALOG_SOURCEEXPLO          197
#define IDD_DIALOG_SOURCEVIBRO          198
#define IDD_DIALOG_SOURCESHOTSETUP      199
#define IDC_COMPANY_URL                 1041
#define IDC_BUTTONGO                    1053
#define IDC_BUTTONSTOP                  1054
#define IDC_BUTTONABORT                 1055
#define IDC_STATIC_ACTIVESOURCEGROUP    1056
#define IDC_STATIC_BLASTER              1057
#define IDC_STATIC_UPHOLE               1058
#define IDC_STATIC_TB                   1059
#define IDC_EDIT_TB                     1060
#define IDC_EDIT_UPHOLE                 1061
#define IDC_ACTIVESOURCE_BUTTON         1062
#define IDC_ACTIVESOURCE_ONE            1062
#define IDC_ACTIVESOURCE_TWO            1063
#define IDC_BUTTON_APPLY                1063
#define IDC_ACTIVESOURCE_THREE          1064
#define IDC_BUTTON_RESET                1064
#define IDC_ACTIVESOURCE_FOUR           1065
#define IDC_STATIC_GRID_EDIT            1065
#define IDC_ACTIVESOURCE_FIVE           1066
#define IDC_BUTTON_ADD                  1066
#define IDC_ACTIVESOURCE_SIX            1067
#define IDC_BUTTON_CHANGE               1067
#define IDC_ACTIVESOURCE_SEVEN          1068
#define IDC_BUTTON_DELETE               1068
#define IDC_ACTIVESOURCE_EIGHT          1069
#define IDC_STATIC_TAB                  1069
#define IDC_ACTIVESOURCE_NINE           1070
#define IDC_STATIC_GRID                 1070
#define IDC_ACTIVESOURCE_TEN            1071
#define IDC_STATIC_NB                   1071
#define IDC_STATIC_LABEL                1072
#define IDC_STATIC_SHOOTERNB            1073
#define IDC_STATIC_INCRNB               1074
#define IDC_STATIC_COMMENT              1075
#define IDC_STATIC_FLEETNB              1076
#define IDC_STATIC_TYPEOFMOVING         1077
#define IDC_STATIC_STEP                 1078
#define IDC_STATIC_WORKBYACQ            1079
#define IDC_STATIC_CLUSTERNB            1080
#define IDC_STATIC_SHOTID               1081
#define IDC_STATIC_BREAKPOINT           1082
#define IDC_STATIC_SWATHNB              1083
#define IDC_STATIC_LINE                 1084
#define IDC_STATIC_SOURCE               1085
#define IDC_STATIC_RCV                  1086
#define IDC_STATIC_SPREAD               1087
#define IDC_STATIC_SFL                  1088
#define IDC_STATIC_SFN                  1089
#define IDC_STATIC_TYPE                 1090
#define IDC_STATIC_SUPERSPREAD          1091
#define IDC_STATIC_PROCTYPE             1092
#define IDC_BUTTON_REVERSE              1093
#define ID_VIEW_CUSTOMIZE               32770
#define ID_VIEW_TOOLBARS                32771
#define ID_VIEW_ALLVPBAR                32792
#define ID_VIEW_USER_TOOLBAR1           32793
#define ID_VIEW_USER_TOOLBAR2           32794
#define ID_VIEW_USER_TOOLBAR3           32795
#define ID_VIEW_USER_TOOLBAR4           32796
#define ID_VIEW_USER_TOOLBAR5           32797
#define ID_VIEW_USER_TOOLBAR6           32798
#define ID_VIEW_USER_TOOLBAR7           32799
#define ID_VIEW_USER_TOOLBAR8           32800
#define ID_VIEW_USER_TOOLBAR9           32801
#define ID_VIEW_USER_TOOLBAR10          32802
#define ID_VIEW_ACTIVESOURCEBAR         32803
#define ID_VIEW_OUTPUT                  32804
#define ID_VIEW_VPDONEBAR               32805
#define ID_VIEW_VPTODOBAR               32806
#define ID_TOOLBAR_SETUP                32807
#define ID_TOOLBAR_VIEW                 32808
#define ID_VPSHOT_FROM                  32809
#define ID_ALLVP_ONE                    32809
#define ID_ALLVP_TWO                    32810
#define ID_ALLVP_THREE                  32811
#define ID_ALLVP_FOUR                   32812
#define ID_ALLVP_FIVE                   32813
#define ID_ALLVP_SIX                    32814
#define ID_ALLVP_SEVTEN                 32815
#define ID_ALLVP_EIGHT                  32816
#define ID_ALLVP_NINE                   32817
#define ID_ALLVP_TEN                    32818
#define ID_VPTODO_ONE                   32819
#define ID_VPTODO_TWO                   32820
#define ID_VPTODO_THREE                 32821
#define ID_VPTODO_FOUR                  32822
#define ID_VPTODO_FIVE                  32823
#define ID_VPTODO_SIX                   32824
#define ID_VPTODO_SEVTEN                32825
#define ID_VPTODO_EIGHT                 32826
#define ID_VPTODO_NINE                  32827
#define ID_VPTODO_TEN                   32828
#define ID_VPDONE_ONE                   32829
#define ID_VPDONE_TWO                   32830
#define ID_VPDONE_THREE                 32831
#define ID_VPDONE_FOUR                  32832
#define ID_VPDONE_FIVE                  32833
#define ID_VPDONE_SIX                   32834
#define ID_VPDONE_SEVTEN                32835
#define ID_VPDONE_EIGHT                 32836
#define ID_VPDONE_NINE                  32837
#define ID_VPDONE_TEN                   32838
#define ID_ACTIVESOURCE_SOURCE          32850
#define ID_ACTIVESOURCE_DISASSOCIATEVP  32851
#define ID_ACTIVESOURCE_ASSOCIATEVP     32852
#define ID_ACTIVESOURCE_CLEANREADY      32853
#define ID_ACTIVESOURCE_ASSOCIATESPLSPN 32854
#define ID_VPSELECT_VPSELECTED          32855
#define ID_SETUP_SOURCE                 32858
#define ID_SETUP_OPERATION              32859
#define ID_SETUP_PROCESSTYPE            32860
#define ID_SETUP_NOISEEDITING           32861
#define ID_SETUP_COMMENTS               32862
#define ID_SETUP_OPTIONS                32863
#define ID_SETUP_DELAYSETUP             32864
#define ID_SETUP_PREFERENCES            32865
#define ID_VIEW_ACTIVEACQBAR            32868
#define ID_VIEW_OPERATIONREPORTBAR      32869
#define ID_VIEW_VPSOURCE                32870
#define ID_VIEW_VPSOURCEBAR             32877
#define ID_VIEW_GRAPHBAR                32878
#define ID_INDICATOR_CONNECT            59142
#define IDS_CONNECTSERVER_ICON          59143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        200
#define _APS_NEXT_COMMAND_VALUE         32879
#define _APS_NEXT_CONTROL_VALUE         1095
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
